### ISSUE TITLE
Redesign "blue bar" menu for works and collections

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1065]
# Feature Request

Redesign the blue bar to make it easier to get to the draft if it exists.

Some ideas we're considering:

- [x] A single button to create/edit the draft regardless of the version you're looking at #1078 
- [x] An Admin-only button to edit a particular version #1078 
- [x] A "Preview Draft" button to jump to the draft version #1079
- [x] Move the version navigator to the side bar. #1080

Still brainstorming. We will probably need to try these out in a preview branch before we decide what works best.
