### ISSUE TITLE
Accessibility testing of blue bar and creator search UI updates

### ISSUE THREAD

**Issue by binkylush** [psu-libraries/scholarsphere#1089]
Screen reader testing to confirm accessibility of recent/upcoming ui changes to blue bar, version nav and creator search:

- #1065 
- #1080 
- #945
- #893 
- #891

**Comment by binkylush** [comment]
Accessibility testing instructions for screen reader testing.

[SS testing - 1.24.docx](https://github.com/psu-libraries/scholarsphere/files/13908338/SS.testing.-.1.24.docx)

**Comment by binkylush** [comment]
To test:
Summary – 37:00
https://psu.mediaspace.kaltura.com/media/1_apj74i9w


- [x] [Test Update work button](https://github.com/psu-libraries/scholarsphere/issues/1078)
 - Works as expected

- [x] [Update collection button](https://github.com/psu-libraries/scholarsphere/issues/1078)
 - Works as expected

- [x] [View preview (if there is a draft version)](https://github.com/psu-libraries/scholarsphere/issues/1079)
 - Works as expected

- [x] [Reading of version info moved to right hand side](https://github.com/psu-libraries/scholarsphere/issues/1080)
- Works as expected

- [x] [Creator search results not getting read back with the screen reader#890](https://github.com/psu-libraries/scholarsphere/issues/890) 
- Works as expected

- [ ] [Test adding a new contributor](https://github.com/psu-libraries/scholarsphere/issues/945)
- Field below add another creator just says “search” – it should say "Search for creator to add" 
- Once a name is selected, it doesn’t tell you that it has been selected 

- [x] [Hit enter after adding new contributor to make sure focus goes to display name](https://github.com/psu-libraries/scholarsphere/issues/893)
- This currently takes you to the Search for add another contributor. It should take you to display name so you can make sure all fields are completed/correct

- [x] When a user goes to the Add acknowledgement field, the text reads "add another link”. This should read “Add an acknowledgement” (18:10 on recording)

- [ ] Consistency across bottom – on the edit works page at the bottom of the page - Save and Continue, Save Draft and Exit, Cancel, and Delete - some of these are buttons and some links (19:20 on recording)

- [x] Screen reader user not made aware of error. An error came up when trying to save a draft and the screen reader was not notified of the error.(20:00 on recording) When I pointed it out, Michelle could navigate to it, but she had no way of knowig that there was an error that was keeping her from saving the draft.

**Comment by binkylush** [comment]
Recording for issues identified above: [https://psu.mediaspace.kaltura.com/media/1_apj74i9w](https://psu.mediaspace.kaltura.com/media/1_apj74i9w)

**Comment by binkylush** [comment]
@jlandiseigsti - Here is the SiteImprove report with a few additional small accessibility changes from our automated checker. I thought you had an account - but realize that you did not, so you'll need to create a password and login to see this report: [https://my2.siteimprove.com/Accessibility/845835/NextGen/IssuesOverview/1?conformance=&pageSegments=&issueKind=1&difficulty=&elementType=&responsibility=0&exceptTags=1,2&includingTags=](https://my2.siteimprove.com/Accessibility/845835/NextGen/IssuesOverview/1?conformance=&pageSegments=&issueKind=1&difficulty=&elementType=&responsibility=0&exceptTags=1,2&includingTags=)

**Comment by jlandiseigsti** [comment]
Thanks! I'll check it out

**Comment by jlandiseigsti** [comment]
Regarding consistency across the bottom, there is a way to do it with all buttons, but it would be a lot refactoring. Essentially, the Rails' `button_to` creates a form...but in this case, we're already within a form and html ignores the inner one. This leads to the call going to the incorrect resource. 

A way around this: by using `button_tag` instead, you can assign it to a form, a la `<%= button_tag, form: 'some_form'%> Then, _outside_ of the other form, you can define "some_form", with the logic that it needs. But because of the way we've broken everything into little components and partials, there's a surprising amount of refactoring that this entails. Given that usability isn't currently a problem, I don't feel like this is worth it at the moment.
