### ISSUE TITLE
Fix how we link users to ORCIDs

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1198]
# Feature Request

The user-editable field for ORCIDs on the profile page was a bad idea. It's an anti-pattern and we should fix it. We should also check how these user-entered IDs are used.

- [x] #518 
- [x] #1199
- [x] How many users in ScholarSphere have user-entered ORCIDS?
    - **Answer:** 70 as 0f 2022-01-27
- [x] When to sync ORCIDS?
  - [x] On user login
- [x] Email users who have entered their orcid and encourage them to link it centrally with PSU.
See also:
- #1160 
-  #1193

**Comment by srerickson** [comment]
emails have been sent to users who need to link their orcids centrally. I think this issue can be closed now
