### ISSUE TITLE
4.13 Post-Release Tasks

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/scholarsphere#1251]
- [x] Autogenerate thumbnails for all existing works
- [x] Run `bundle exec rake migration:set_thumbnail_selections` (re #1283)
- [x] Run `BackfillData::PopulateAasmTimestamps` (re: #1255)
- [x] Reindex works and collections for thumbnails + drafts in collections
- [x] Add ScholarSphere to Unpaywall: https://unpaywall.org/sources
- [x] Delete `BackfillData` classes from repo
- [ ] Generate checksums for files (re: #1237)

**Comment by srerickson** [comment]
Should we add task for generating checksums (if we don't have them)?

**Comment by nicktiberi** [comment]
> Should we add task for generating checksums (if we don't have them)?

Good call — I added that to the task list.

**Comment by whereismyjetpack** [comment]
I'll run the thumbnail jobs, and signature jobs the week of the 14th. I want to run them after we get #1269 merged.

**Comment by whereismyjetpack** [comment]
checksums is filling up node disks while it's processing, i'm doing some investigation on where the temp IO object lives, and I will work on mounting that as a volume (if possible)

**Comment by srerickson** [comment]
@whereismyjetpack can this be closed?

**Comment by whereismyjetpack** [comment]
There's a bug that we need to address in the next scholarsphere cycle before we can complete this.
