### ISSUE TITLE
Testing Migration Data

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#35]
Work on migrating some data to make sure our models wont create any problems with migrating our current data set.

## Related Tickets
- [x]  Migration Data Report #61 
- [x]  Define Migration Process #72 

## Blocks

This is partially blocked by #115, which must be completely finished before we can migrate all types of our data, but as some of the subtickets are completed, we can run limited tests of migrating data.

## TODO

- [x] Collect LDAP group information for users #37 
- [x] Implement ACLs #116 
- [x] API endpoint for new work #115
- [x] In SS3: enable multipart upload, likely via rake or command line, using the AWS SDK
- [x] In SS3: create a rake task to push existing works into SS4 via the API endpoint

See https://github.com/psu-stewardship/scholarsphere/commit/e37f4462a0b28b55412b75f8611181d9225b68ba

**Comment by DanCoughlin** [comment]
We need to identify a couple types of works in current ScholarSphere, that are potentially problematic. 

- A work that has many versions of files. So we have to deal with many versions of files.
- A work that is in a collection -- how are we going to deal with collections
- A work with one file (likely a common work)

Seth will add more potential problematic works for us to look at and add to this ticket.
