### ISSUE TITLE
UI for Creating and Managing Collections

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#718]
Duplicate the existing workflow for searching, creating, and editing works.

- [x] add work type facet to the dashboard to so that users can find their collections in the dashboard #516 
- [x] add edit and "collection settings" buttons to the resource display page for collections #741
- [x] duplicate work form for editing collections #742
- [x] add collection settings page with dois and editors options #743
- [x] mint DOIs for collections #313
- [x] add link to create new collection in the user dropdown menu #744
