### ISSUE TITLE
Remodeling Creators in Work and Collections

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#817]
# Feature Request

We need to be able to add creators both with and without identifiers, and differentiate between them.

## Linked Tickets

- [x] Update database schema with new authorship model requirements (#818)
- [x] Migrate data to new Authorship table (#819)
- [x] Integrate with Orcid to query known ids (#820)
- [x] Update UI to reflect new requirements when adding creators (#821)
