### ISSUE TITLE
Removed deprecated *Creation code and data

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#847]
Once we've completed implementing the new authorship model and migrating the data, we can removed the old model code and delete the tables.

Blocked by #817 

- [x] Remove WorkVersionCreation and CollectionCreation models, referenced methods, and their data #875
- [x] Remove unidentified actors and their references to Authorships #874
- [x] Remove ActorsController, related views, and Stimulus controllers #877
