### ISSUE TITLE
Current API needs to reflect the current UI

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#899]
Because the initial API was meant to support migration, there are certain features that should be change in order to support other integrations, such as the Researcher metadata database.

## TODO

- [x] Update API validations to match UI validations (#909)
- [x] Make creating actors easier and less error-prone (#910)
- [x] Update PublishNewWork service (#898)
